CREATE TABLE navigationbar (
    id SERIAL PRIMARY KEY,
    navigation_option VARCHAR(255) NOT NULL
);
INSERT INTO navigationbar("navigation_option")
VALUES ('Home'),
    ('Products'),
    ('About Us'),
    ('Ties');
-- Crear tabla de clientes
CREATE TABLE public.clientes (
    cliente_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    correo VARCHAR(100) NOT NULL UNIQUE,
    area VARCHAR(100),
    mision TEXT
);
-- Crear tabla de pedidos
CREATE TABLE public.pedidos (
    pedido_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT,
    producto VARCHAR(100) NOT NULL,
    cantidad INT NOT NULL,
    precio DECIMAL(10, 2) NOT NULL,
    fecha DATE NOT NULL,
    imagen_factura BOOLEAN DEFAULT FALSE,
    entregado BOOLEAN DEFAULT FALSE,
    reportado BOOLEAN DEFAULT FALSE,
    incompleto BOOLEAN DEFAULT FALSE,
    comentarios TEXT,
    FOREIGN KEY (cliente_id) REFERENCES public.clientes(cliente_id) ON DELETE CASCADE
);
-- Crear tabla de imagenes de productos
CREATE TABLE public.imagen_productos (
    imagen_producto_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(255) NOT NULL,
    pedido_id BIGINT,
    FOREIGN KEY (pedido_id) REFERENCES public.pedidos(pedido_id) ON DELETE
    SET NULL
);
-- Crear tabla de imagenes de factura
CREATE TABLE public.imagen_factura (
    imagen_factura_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(255) NOT NULL,
    pedido_id BIGINT,
    FOREIGN KEY (pedido_id) REFERENCES public.pedidos(pedido_id) ON DELETE CASCADE
);